name: CI/CD for react Todo 

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd todo
          npm install

      - name: Build Project
        run: |
          cd todo
          npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: poduction file
          path: ./todo/build

  # Deploy Job
  deploy:
   
    needs: build
    
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: poduction file
          path: ./todo/build

      #- name: Deploy to GitHub Pages
       # uses: peaceiris/actions-gh-pages@v4
        #if: github.ref == 'refs/heads/main'
       # with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }} #this is the key of the access token
         # publish_dir: ./todo/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
